version: '3'
services:
  pdf-generator:
    build:
      context: .
      args:
        VARIANT: 16
    # Override the command so that the container does not shut down
    command: node /app/src/index.js

    ports:
      - 3005:3005
    volumes:
      - .:/app:rw
    environment:
      - PORT=3005
