version: '3'
services:
  pdf-generator:
    build:
      context: .
      args:
        VARIANT: 16
    # Override the command so that the container does not shut down
    command: yarn start

    security_opt:
      - seccomp=./src/lib/chrome.json
    ports:
      - 3005:3005
    volumes:
      - .:/app:cached
    environment:
      - PORT=3005
