version: '3'
services:
  devcontainer:
    build:
      context: .
      args:
        VARIANT: 16
    # Override the command so that the container does not shut down
    command: sleep infinity
    environment:
      - PORT=3005
