version: '3'
services:
  devcontainer:
    build:
      context: .
    # Override the command so that the container does not shut down
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    environment:
      - PORT=3005
